[package]
name = "token-shrinker-update"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
token-shrinker-config.workspace = true
token-shrinker-protocol.workspace = true
token-shrinker-types.workspace = true

[lints]
workspace = true
