[package]
name = "token-shrinker-update"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
token-shrinker-config.workspace = true
token-shrinker-protocol.workspace = true
token-shrinker-types.workspace = true

[lints]
workspace = true
