[package]
name = "token-shrinker-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
token-shrinker-compress.workspace = true
token-shrinker-types.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
